
package bookClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookServiceInterface", targetNamespace = "http://applicationservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookServiceInterface {


    /**
     * 
     * @param bookId
     * @return
     *     returns bookClient.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookById", targetNamespace = "http://applicationservice.com/", className = "bookClient.GetBookById")
    @ResponseWrapper(localName = "getBookByIdResponse", targetNamespace = "http://applicationservice.com/", className = "bookClient.GetBookByIdResponse")
    @Action(input = "http://applicationservice.com/BookServiceInterface/getBookByIdRequest", output = "http://applicationservice.com/BookServiceInterface/getBookByIdResponse")
    public Book getBookById(
        @WebParam(name = "book_id", targetNamespace = "")
        String bookId);

    /**
     * 
     * @return
     *     returns java.util.List<bookClient.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://applicationservice.com/", className = "bookClient.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://applicationservice.com/", className = "bookClient.GetAllBooksResponse")
    @Action(input = "http://applicationservice.com/BookServiceInterface/getAllBooksRequest", output = "http://applicationservice.com/BookServiceInterface/getAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeBook", targetNamespace = "http://applicationservice.com/", className = "bookClient.RemoveBook")
    @ResponseWrapper(localName = "removeBookResponse", targetNamespace = "http://applicationservice.com/", className = "bookClient.RemoveBookResponse")
    @Action(input = "http://applicationservice.com/BookServiceInterface/removeBookRequest", output = "http://applicationservice.com/BookServiceInterface/removeBookResponse")
    public String removeBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateBook", targetNamespace = "http://applicationservice.com/", className = "bookClient.UpdateBook")
    @ResponseWrapper(localName = "updateBookResponse", targetNamespace = "http://applicationservice.com/", className = "bookClient.UpdateBookResponse")
    @Action(input = "http://applicationservice.com/BookServiceInterface/updateBookRequest", output = "http://applicationservice.com/BookServiceInterface/updateBookResponse")
    public String updateBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBook", targetNamespace = "http://applicationservice.com/", className = "bookClient.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://applicationservice.com/", className = "bookClient.AddBookResponse")
    @Action(input = "http://applicationservice.com/BookServiceInterface/addBookRequest", output = "http://applicationservice.com/BookServiceInterface/addBookResponse")
    public String addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

}
