
package bookClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookServiceImplementationService", targetNamespace = "http://applicationservice.com/", wsdlLocation = "http://localhost:8082/books?wsdl")
public class BookServiceImplementationService
    extends Service
{

    private final static URL BOOKSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName BOOKSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://applicationservice.com/", "BookServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/books?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        BOOKSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public BookServiceImplementationService() {
        super(__getWsdlLocation(), BOOKSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public BookServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public BookServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, BOOKSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public BookServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public BookServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookServiceInterface
     */
    @WebEndpoint(name = "BookServiceImplementationPort")
    public BookServiceInterface getBookServiceImplementationPort() {
        return super.getPort(new QName("http://applicationservice.com/", "BookServiceImplementationPort"), BookServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookServiceInterface
     */
    @WebEndpoint(name = "BookServiceImplementationPort")
    public BookServiceInterface getBookServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://applicationservice.com/", "BookServiceImplementationPort"), BookServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw BOOKSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return BOOKSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
